/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef ROBOTBESTURING_PRIVATE_H
#define ROBOTBESTURING_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.3.1.2801"
#define VER_MAJOR	1
#define VER_MINOR	3
#define VER_RELEASE	1
#define VER_BUILD	2801
#define COMPANY_NAME	"Mes en Fieback en Co."
#define FILE_VERSION	"1.3.1.2801"
#define FILE_DESCRIPTION	"Robotbesturing"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Porno"
#define PRODUCT_VERSION	"1.3.1.2801"

#endif /*ROBOTBESTURING_PRIVATE_H*/
